name: {{project_name.snakeCase()}}
repository: {{{github_url}}}

packages:
  - {{project_name.snakeCase()}}
  - {{project_name.snakeCase()}}_core

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  test:
    name: test
    description: 'Run all tests'
    run: |
      melos exec --fail-fast                                  -- flutter analyze . && \
      melos exec --fail-fast --dir-exists="test" --no-flutter -- flutter test . && \
      melos exec --fail-fast --dir-exists="test" --flutter    -- flutter test .